/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 headphones.glb --transform 
Files: headphones.glb [675.32KB] > D:\Web Development\Projects\3D Showcase Web\public\headphones-transformed.glb [638.6KB] (5%)
*/

import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    `${import.meta.env.BASE_URL}headphones-transformed.glb`,
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Lower.geometry}
        material={materials.LowerC}
        position={[1.239, -0.077, 0.155]}
        rotation={[-0.061, -0.682, -0.253]}
        scale={0.098}
      />
      <mesh
        geometry={nodes.Upper.geometry}
        material={materials.UpperC}
        position={[0.014, 0.102, -0.038]}
        rotation={[-0.063, -0.677, -0.448]}
        scale={[0.006, 0.006, 0.017]}
      />
      <mesh
        geometry={nodes.UpperFoam.geometry}
        material={materials.UpperFoamC}
        position={[0.014, 0.106, -0.038]}
        rotation={[-0.063, -0.677, 0]}
        scale={0.098}
      />
      <mesh
        geometry={nodes.Ear.geometry}
        material={materials.EarC}
        position={[0.014, -0.154, -0.021]}
        rotation={[-0.061, -0.682, -0.253]}
        scale={0.098}
      />
      <mesh
        geometry={nodes.Foam.geometry}
        material={materials.FoamC}
        position={[0.014, -0.142, -0.022]}
        rotation={[-0.061, -0.682, -0.253]}
        scale={0.098}
      />
      <mesh
        geometry={nodes.Fabric.geometry}
        material={materials.FabricC}
        position={[0.014, -0.148, -0.022]}
        rotation={[-0.061, -0.682, -0.253]}
        scale={0.098}
      />
    </group>
  );
}

useGLTF.preload(`${import.meta.env.BASE_URL}headphones-transformed.glb`);
